### ISSUE TITLE
year in date-picker is suddenly Gregorian after updating dayjs and antd

### ISSUE THREAD

**Issue by mohas** [saeedrahimi/antd-jalali#22]
Hi, thank you for awesome work on the library, I notice that after updating dayjs and antd in my project to versions 1.11.0 and 4.19.3 respectively, year in date-picker turned into Gregorian year (2022), can you have a look. 

I tried to fork and build the lib myself but it seems that the latest version on react-script is incompatible with your project structure, it needs the library to be in the src folder while it is in the lib folder, also I noticed a `getFirstWeekDate` is added to dayjs interface which is not implemented.

would you be interested in a separate demo folder for vercel app? or a storybook?

**Comment by amirfahmideh** [comment]
Thanks for your library, I have been using in my react projects, but same for me after updating to new version, when you try to use react-script we get the error and the cause is library should be in source folder

![Screenshot 2022-04-10 080835](https://user-images.githubusercontent.com/35830405/162600472-08e72b57-569f-430b-91d9-658c225ff4ec.jpg)

**Comment by saeedrahimi** [comment]
Thank you for the report. I will fix it when I have time. Or you can send a pull request and I will merge it into the code.
