### ISSUE TITLE
Error styles

### ISSUE THREAD

**Issue by mehdiraized** [saeedrahimi/antd-jalali#6]
Unexpected character '@'

```
nextjs: 10.0.2
react: 17.0.1
```

```
./node_modules/antd/lib/calendar/style/index.less 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import '../../style/themes/index';
| @import '../../style/mixins/index';
```

![Screen Shot 1399-09-03 at 17 27 29](https://user-images.githubusercontent.com/4368004/99970515-2e0d0a80-2db1-11eb-9e97-b4d25eaabf01.png)

**Comment by saeedrahimi** [comment]
there was an issue with CommonJs and now it is fixed in library.

also i provided a demo in next.js
Repo: https://github.com/saeedrahimi/nextjs-antd-jalali-example Live Demo: https://nextjs-antd-jalali-example.vercel.app/

hint: In nextjs you should load datepicker (or all ant-design) styles manually.
