### ISSUE TITLE
antd-jalali datepicker problem when setting initial value via form instance

### ISSUE THREAD

**Issue by badie21** [saeedrahimi/antd-jalali#8]
when i'm trying to set initial value for jalali datepicker via form.setFieldsValue the datepicker popup container goes crazy and i can't figure the problem and you can not select a date until you choose the today date and then it is possible to choose date
![Screenshot (22)](https://user-images.githubusercontent.com/54777505/102499955-0b5cd180-4091-11eb-8278-c953591643d7.png)

this is the part of my code that i'm trying to set datePicker initial value

```
form.setFieldsValue({
        
        date: moment(DATE, 'YYYY-MM-DD'),
      })
 <Form.Item name="date" label="تاریخ قرارداد" labelCol={{ span: 24 }}>
                <JalaliDatePicker
                  format="YYYY-MM-DD"
                  style={{ width: '100%' }}
                />
              </Form.Item>
```

**Comment by badie21** [comment]
form.setFieldsValue({
                date: moment(selectedField.contract.datetime, 'YYYY-MM-DD'),
        // dateTo: moment(selectedField.contract.datetimeTo, 'YYYY-MM-DD').locale('fa'),
      })

**Comment by badie21** [comment]
i used day.js to get the object of date and then set that as initial value

```
date: dayjs(
          Jmoment.from(selectedField.contract.datetime, 'YYYY-MM-DD')
            .locale('fa')
            .format('YYYY-MM-DD'),
        ).locale('fa')
```

**Comment by mehdi-ard** [comment]
i used [day.js](https://day.js.org/) and [jalaliday](https://github.com/alibaba-aero/jalaliday) for initial value : 
```
const date = dayjs(date).calendar('jalali').locale('fa')

 <DatePickerJalali
format={'YYYY/MM/DD'}
value={date }
/>
```

**Comment by AliAmini** [comment]
Hi Saeed

Are you sure that default value will work with dayjs object?
I try it in diffrent ways, but I didn't get any hopeful results.

when you set default value with **dayjs** object, it will throw:

```
TypeError: clone.weekday is not a function
```

because `clone().weekday()` is a function of **moment**, not **dayjs**.
I think you did wrong.
Currently, the only way of setting default data is **moment**.  But when the value set by `moment`, it goes crasy because you mixed up `moment` and `dayjs`.

Can you set a default value in your demo page?
